environments:
  dev:
    values:
      - values-dev.yaml 
  stage:
    values:
      - values-stage.yaml  

---
repositories:
  - name: reto-tecnico
    url: https://hansleolml.github.io/reto_tecnico/helm

releases:
  - name: reto-tecnico
    namespace: '{{ .Environment.Name }}'
    chart: reto-tecnico/reto-tecnico
    values: 
      - values-{{ .Environment.Name }}.yaml 
    secrets:
      - ./secrets2.yaml