apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-v2
  namespace: ingressns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-v2
  template:
    metadata:
      labels:
        app: hello-v2
    spec:
      containers:
      - name: hello
        image: nginxdemos/hello
        ports:
        - containerPort: 8080